name: krillkafka
# Will add more later, maybe turn this into kubernetes
services:
   kafka:
    image: docker.io/apache/kafka:4.2.0
    container_name: kafka
    ports:
      - "9092:9092"
    volumes:
      - kafka_data:/var/lib/kafka/data
      - ./config:/mnt/shared/config:rw,z

volumes:
  kafka_data:
