bootstrap_servers = ["127.0.0.1:9092"]
# TODO: remove these in future
csv_sim_path = "graveyard/test.csv"
csv_header_path = "graveyard/NUSW-NB15_features.csv"

[kafka_config]
bootstrap_servers = ["127.0.0.1:9092"]
retries = 3
acks = 1

[simulation]
# path to file csv data
csv_sim_path = "graveyard/test.csv"
# path to csv feature file
csv_header_path = "graveyard/NUSW-NB15_features.csv"
