[kafka]
# Can be overrided by KAFKA_BOOTSTRAP_SERVERS
bootstrap_servers = ["localhost:9092"]
# Some kafka configs taken in https://kafka.apache.org/42/configuration/producer-configs/
# maybe put these in another table?
retries = 3
acks = "all"

[simulation]
# path to file csv data
csv_sim_path = "graveyard/UNSW-NB15.csv"
# path to csv feature file
csv_header_path = "graveyard/NUSW-NB15_features.csv"
