apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\Windows\system32\kompose.exe convert -f docker-compose.yml -o serving/kubernetes/ --volumes emptyDir
    kompose.version: 1.31.2 (a92241f79)
  creationTimestamp: null
  labels:
    io.kompose.service: datanode
  name: datanode
spec:
  ports:
    - name: "9864"
      port: 9864
      targetPort: 9864
  selector:
    io.kompose.service: datanode
status:
  loadBalancer: {}
