apiVersion: apps/v1
kind: Deployment
metadata:
  name: datanode
spec:
  replicas: 1
  selector:
    matchLabels:
      app: datanode
  template:
    metadata:
      labels:
        app: datanode
    spec:
      containers:
      - name: datanode
        image: bde2020/hadoop-datanode:2.0.0-hadoop3.2.1-java8
        ports:
        - containerPort: 9864
        env:
        - name: CORE_CONF_fs_defaultFS
          value: "hdfs://namenode:8020"
        - name: HDFS_CONF_dfs_replication
<<<<<<< HEAD
          value: "1"
=======
          value: "1"
        resources:
          requests:
            memory: "64Mi"
            cpu: "100m"
          resources:
          limits:
            memory: "128Mi"
            cpu: "300m"
>>>>>>> feature/serving-layer
