apiVersion: apps/v1
kind: Deployment
metadata:
  name: jupyter-cluster
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jupyter
  template:
    metadata:
      labels:
        app: jupyter
    spec:
      containers:
      - name: jupyter
        image: jupyter/pyspark-notebook
        ports:
        - containerPort: 8888
<<<<<<< HEAD
=======
        resources:
          requests:
            memory: "64Mi"
            cpu: "100m"
          resources:
          limits:
            memory: "128Mi"
            cpu: "300m"
>>>>>>> feature/serving-layer
---