apiVersion: v1
kind: Service
metadata:
  name: namenode
spec:
  selector:
    app: namenode
  type: NodePort
  ports:
  - name: web
    port: 9870
    targetPort: 9870
    nodePort: 30870
  - name: rpc
    port: 8020
    targetPort: 8020
    nodePort: 30820

